Dfsdfmember input
ansible-collections/ibm_zos_ims pull request #114
Opened 2023-09-22 21:47 UTC by steph-lieu

##### SUMMARY

Created a new input for the DFSDFxxx member in the IMS.PROCLIB data set where the CATALOG section is defined. It was previously hard-coded as "CAT", but now the user can specify what member they want to use. For example, desdf_member: "CAT" specifies the DFSDFCAT member of the PROCLIB data set.

##### ISSUE TYPE

- Enhancement Pull Request

##### COMPONENT NAME

DFSDFxxx member input

2023-09-26 18:01 UTC, trevinop36 reviewed
The test cases were executed and have returned code 0

2023-09-27 18:13 UTC, ddgandhi requested changes
If you can delete vars_files from ims-collection-sample as host_vars folder is not shipped in the dev branch.

2023-10-04 19:40 UTC, some-ibmer commented
@ddgandhi Can we merge this PR now?

2023-10-04 20:47 UTC, ddgandhi approved these changes

2023-10-09 15:00 UTC, merged